name: Release LoomIn
on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Build and Release LoomIn
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Assemble Loom Library
        run: ./gradlew :loom:assemble
      - name: Debug Secrets

        run: |
          echo "GPR_USERNAME: ${{ secrets.GPR_USERNAME }}"
          echo "GPR_TOKEN: ${{ secrets.GPR_TOKEN }}"

      - name: Publish Loom to GitHub Packages
        run: ./gradlew :loom:publish -Pgpr.user=${{ secrets.GPR_USERNAME }} -Pgpr.token=${{ secrets.GPR_USERNAME }}
        env:
          GPR_USERNAME: ${{ secrets.GPR_USERNAME }}
          GPR_TOKEN: ${{ secrets.GPR_TOKEN }}
