name: Release LoomIn
on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Build and Publish Loom
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Assemble Loom Library
        run: ./gradlew :loom:assemble

      - name: Publish Loom to GitHub Packages
        run: ./gradlew :loom:publish
        env:
          GITHUB_USERNAME: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
