name: test-build
on:
  pull_request:
      branches:
        - main
permissions:
  contents: write

jobs:
  housekeeping:
    name: HouseKeeping
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: ktLint
        run: |
          echo "✅ ktLint pass"
  security:
    name: Security
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check CODE_OWNERS
        run: |
          echo "✅ CODE_OWNERS passed"
#            if [ ! -f ".github/CODEOWNERS" ]; then
#              echo "❌ CODE OWNERS file is missing"
#              exit 1
#            else
#              echo "✅ CODE OWNERS file exists"
#            fi

  test:
    name: Unit test
    runs-on: ubuntu-latest
    needs: [housekeeping, security]
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Run unit test
        run: |
          ./gradlew test --no-daemon
  build:
    name: Build APKs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build APK
        run: |
          ./gradlew :app:assembleDebug --no-daemon